-- ============================================================================
-- MASTER SEED LIBRARY DATA
-- ============================================================================
-- Comprehensive seed data for taxonomy-aware library generation
-- Total: 500+ records (Root Causes, Impacts, Controls, KRIs, KCIs)
-- ============================================================================

-- ============================================================================
-- ROOT CAUSES (150+)
-- ============================================================================

INSERT INTO seed_master_library (library_type, code, name, description, category_hints, keyword_hints, industry_tags, metadata) VALUES

-- OPERATIONAL RISK (20)
('root_cause', 'RC-OP-001', 'Inadequate internal controls', 'Weak or missing control frameworks that fail to prevent errors or detect issues', ARRAY['Operational', 'Operational Risk', 'Process', 'Internal Controls'], ARRAY['control', 'process', 'compliance', 'framework'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-OP-002', 'Insufficient capacity or resources', 'Limited staff, budget, infrastructure, or technology capacity to meet operational demands', ARRAY['Operational', 'Resource', 'Capacity'], ARRAY['capacity', 'resource', 'staffing', 'budget'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-003', 'Process inefficiency or failure', 'Poorly designed, outdated, or broken business processes causing delays or errors', ARRAY['Operational', 'Process'], ARRAY['process', 'workflow', 'inefficiency', 'bottleneck'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-004', 'Infrastructure breakdown', 'Failure of critical physical infrastructure supporting operations', ARRAY['Operational', 'Infrastructure'], ARRAY['infrastructure', 'facilities', 'equipment', 'breakdown'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-OP-005', 'Supply chain disruption', 'Interruption to critical suppliers, logistics, or procurement channels', ARRAY['Operational', 'Supply Chain'], ARRAY['supply chain', 'vendor', 'logistics', 'procurement'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-OP-006', 'Quality control failures', 'Inadequate quality assurance processes leading to defects', ARRAY['Operational', 'Quality'], ARRAY['quality', 'QA', 'defect', 'testing'], ARRAY['manufacturing', 'healthcare', 'pharmaceuticals', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-007', 'Human error', 'Mistakes made by personnel in executing tasks or processes', ARRAY['Operational', 'Human'], ARRAY['human error', 'mistake', 'personnel', 'manual'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-008', 'Single points of failure', 'Critical dependencies on single systems, processes, or individuals', ARRAY['Operational', 'Resilience'], ARRAY['single point', 'dependency', 'critical', 'redundancy'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-OP-009', 'Inadequate business continuity planning', 'Lack of disaster recovery or crisis management plans', ARRAY['Operational', 'Business Continuity', 'Resilience'], ARRAY['BCP', 'disaster recovery', 'continuity', 'crisis'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-OP-010', 'Geographic concentration risk', 'Over-reliance on single geographic locations for operations', ARRAY['Operational', 'Geographic'], ARRAY['geographic', 'concentration', 'location', 'regional'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-011', 'Outdated equipment or technology', 'Aging systems or machinery requiring replacement', ARRAY['Operational', 'Technology', 'Infrastructure'], ARRAY['legacy', 'outdated', 'aging', 'obsolete'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-012', 'Maintenance failures', 'Inadequate preventive maintenance programs', ARRAY['Operational', 'Maintenance'], ARRAY['maintenance', 'preventive', 'breakdown', 'repair'], ARRAY['manufacturing', 'energy_utilities', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-013', 'Inventory management issues', 'Poor inventory control causing stockouts or overstock', ARRAY['Operational', 'Inventory', 'Supply Chain'], ARRAY['inventory', 'stock', 'warehouse', 'supply'], ARRAY['retail', 'manufacturing', 'universal'], '{"severity_indicator": "Low"}'::jsonb),
('root_cause', 'RC-OP-014', 'Transportation and logistics failures', 'Breakdowns in shipping or distribution networks', ARRAY['Operational', 'Logistics', 'Supply Chain'], ARRAY['logistics', 'transportation', 'shipping', 'distribution'], ARRAY['retail', 'manufacturing', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-015', 'Project management failures', 'Inadequate planning, execution, or oversight of projects', ARRAY['Operational', 'Project'], ARRAY['project', 'programme', 'planning', 'execution'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-016', 'Unclear processes and procedures', 'Ambiguous or poorly documented business processes', ARRAY['Operational', 'Process'], ARRAY['process', 'procedure', 'documentation', 'unclear'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-017', 'Inadequate testing', 'Insufficient testing of systems or processes before deployment', ARRAY['Operational', 'Quality', 'Technology'], ARRAY['testing', 'QA', 'validation', 'deployment'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-018', 'Knowledge loss', 'Loss of critical institutional knowledge or expertise', ARRAY['Operational', 'Human Capital'], ARRAY['knowledge', 'expertise', 'institutional', 'documentation'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-OP-019', 'Workload imbalance', 'Uneven distribution of work leading to bottlenecks', ARRAY['Operational', 'Resource'], ARRAY['workload', 'capacity', 'bottleneck', 'balance'], ARRAY['universal'], '{"severity_indicator": "Low"}'::jsonb),
('root_cause', 'RC-OP-020', 'Inadequate vendor management', 'Poor oversight and management of third-party vendors', ARRAY['Operational', 'Third Party', 'Vendor'], ARRAY['vendor', 'supplier', 'third party', 'outsourcing'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),

-- TECHNOLOGY & CYBER RISK (20)
('root_cause', 'RC-CY-001', 'Cyberattack or data breach', 'Malicious hacking, ransomware, phishing, or other cyber intrusions', ARRAY['Technology', 'Cyber', 'Cybersecurity'], ARRAY['cyber', 'hack', 'breach', 'ransomware', 'phishing'], ARRAY['universal'], '{"severity_indicator": "Critical"}'::jsonb),
('root_cause', 'RC-CY-002', 'System vulnerabilities', 'Unpatched software, weak configurations, or security flaws', ARRAY['Technology', 'Cyber', 'Cybersecurity'], ARRAY['vulnerability', 'patch', 'security', 'configuration'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-003', 'Inadequate cybersecurity controls', 'Weak firewalls, insufficient monitoring, or poor access controls', ARRAY['Technology', 'Cyber', 'Cybersecurity'], ARRAY['firewall', 'access control', 'monitoring', 'security'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-004', 'Insider threats', 'Malicious or negligent employees compromising security', ARRAY['Technology', 'Cyber', 'Human'], ARRAY['insider', 'malicious', 'negligent', 'employee'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-005', 'Third-party security failures', 'Vendors or partners with weak security creating supply chain risk', ARRAY['Technology', 'Cyber', 'Third Party'], ARRAY['vendor', 'third party', 'supply chain', 'security'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-006', 'Technology infrastructure failure', 'Outages, crashes, or performance degradation of IT systems', ARRAY['Technology', 'Infrastructure'], ARRAY['outage', 'crash', 'downtime', 'performance'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-007', 'Cloud service provider failures', 'Downtime or security breaches from cloud vendors', ARRAY['Technology', 'Cloud', 'Third Party'], ARRAY['cloud', 'SaaS', 'AWS', 'Azure', 'provider'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-008', 'Legacy system limitations', 'Outdated technology unable to meet business or security needs', ARRAY['Technology', 'Legacy'], ARRAY['legacy', 'outdated', 'obsolete', 'technical debt'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CY-009', 'Data loss or corruption', 'Loss of critical business data due to failures or malicious acts', ARRAY['Technology', 'Data'], ARRAY['data loss', 'corruption', 'backup', 'recovery'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-010', 'AI/ML model failures', 'Algorithmic bias, model drift, or incorrect AI outputs', ARRAY['Technology', 'AI', 'Data'], ARRAY['AI', 'ML', 'algorithm', 'bias', 'model'], ARRAY['technology', 'financial_services', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CY-011', 'Shadow IT', 'Unauthorized technology deployed without IT governance', ARRAY['Technology', 'Governance'], ARRAY['shadow IT', 'unauthorized', 'governance', 'BYOD'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CY-012', 'Poor change management', 'Inadequate processes for managing technology changes', ARRAY['Technology', 'Change Management'], ARRAY['change management', 'deployment', 'release', 'configuration'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CY-013', 'Insufficient disaster recovery', 'Inadequate IT disaster recovery capabilities', ARRAY['Technology', 'Business Continuity'], ARRAY['disaster recovery', 'DR', 'backup', 'failover'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-014', 'Network security weaknesses', 'Vulnerabilities in network infrastructure or segmentation', ARRAY['Technology', 'Cyber', 'Network'], ARRAY['network', 'segmentation', 'firewall', 'perimeter'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-015', 'Identity and access management failures', 'Poor controls over user identities and access rights', ARRAY['Technology', 'Cyber', 'Access'], ARRAY['IAM', 'identity', 'access', 'authentication', 'MFA'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-016', 'Software bugs or defects', 'Errors in software code causing system issues', ARRAY['Technology', 'Quality'], ARRAY['bug', 'defect', 'software', 'code', 'error'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CY-017', 'Integration failures', 'Problems with system integrations or APIs', ARRAY['Technology', 'Integration'], ARRAY['integration', 'API', 'interface', 'middleware'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CY-018', 'Capacity constraints', 'IT systems unable to handle demand', ARRAY['Technology', 'Capacity'], ARRAY['capacity', 'scalability', 'performance', 'load'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CY-019', 'Data center failures', 'Physical data center outages or issues', ARRAY['Technology', 'Infrastructure'], ARRAY['data center', 'power', 'cooling', 'facility'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CY-020', 'Lack of security awareness', 'Insufficient cybersecurity training for staff', ARRAY['Technology', 'Cyber', 'Human'], ARRAY['awareness', 'training', 'phishing', 'social engineering'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),

-- STRATEGIC RISK (15)
('root_cause', 'RC-ST-001', 'Market disruption', 'Disruptive innovations or technologies that obsolete offerings', ARRAY['Strategic', 'Market'], ARRAY['disruption', 'innovation', 'technology', 'competition'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-ST-002', 'Ineffective strategic planning', 'Poor strategic decision-making or misalignment', ARRAY['Strategic', 'Governance'], ARRAY['strategy', 'planning', 'decision', 'alignment'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-ST-003', 'Competitive pressure', 'Aggressive competitors or loss of competitive advantage', ARRAY['Strategic', 'Competition'], ARRAY['competition', 'market share', 'pricing', 'competitor'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-004', 'M&A integration failures', 'Poorly executed mergers, acquisitions, or divestitures', ARRAY['Strategic', 'M&A'], ARRAY['merger', 'acquisition', 'integration', 'divestiture'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-ST-005', 'Changing customer preferences', 'Shifts in consumer tastes or buying behaviors', ARRAY['Strategic', 'Customer', 'Market'], ARRAY['customer', 'preference', 'demand', 'behavior'], ARRAY['retail', 'consumer_goods', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-006', 'Reputational damage', 'Negative publicity or loss of stakeholder trust', ARRAY['Strategic', 'Reputation', 'Governance'], ARRAY['reputation', 'brand', 'publicity', 'trust'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-ST-007', 'Innovation failure', 'Inability to develop new products or capabilities', ARRAY['Strategic', 'Innovation'], ARRAY['innovation', 'R&D', 'product development', 'capabilities'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-008', 'Poor market positioning', 'Ineffective branding or market segmentation', ARRAY['Strategic', 'Marketing'], ARRAY['positioning', 'branding', 'marketing', 'segmentation'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-009', 'Economic downturn', 'Recession or reduced consumer spending', ARRAY['Strategic', 'Economic', 'External'], ARRAY['recession', 'economic', 'downturn', 'spending'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-ST-010', 'Customer concentration', 'Over-reliance on small number of major clients', ARRAY['Strategic', 'Customer', 'Concentration'], ARRAY['concentration', 'customer', 'dependency', 'revenue'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-011', 'Product obsolescence', 'Products becoming outdated or irrelevant', ARRAY['Strategic', 'Product'], ARRAY['obsolescence', 'product', 'lifecycle', 'relevance'], ARRAY['technology', 'manufacturing', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-012', 'Strategic partnership failures', 'Breakdown of key alliances or joint ventures', ARRAY['Strategic', 'Partnership'], ARRAY['partnership', 'alliance', 'joint venture', 'collaboration'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-013', 'Market entry barriers', 'Inability to enter new markets or segments', ARRAY['Strategic', 'Market'], ARRAY['market entry', 'barriers', 'expansion', 'growth'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-014', 'Digital transformation failure', 'Failed or delayed digital initiatives', ARRAY['Strategic', 'Technology', 'Digital'], ARRAY['digital', 'transformation', 'modernization', 'digitization'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-ST-015', 'Business model disruption', 'Fundamental changes that threaten existing business model', ARRAY['Strategic', 'Business Model'], ARRAY['business model', 'disruption', 'transformation', 'viability'], ARRAY['universal'], '{"severity_indicator": "Critical"}'::jsonb),

-- FINANCIAL RISK (15)
('root_cause', 'RC-FN-001', 'Liquidity constraints', 'Insufficient cash flow to meet obligations', ARRAY['Financial', 'Liquidity'], ARRAY['liquidity', 'cash flow', 'funding', 'working capital'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-FN-002', 'Credit risk exposure', 'Risk of counterparty default or non-payment', ARRAY['Financial', 'Credit'], ARRAY['credit', 'counterparty', 'default', 'payment'], ARRAY['financial_services', 'banking', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-FN-003', 'Market volatility', 'Adverse movements in interest rates, FX, or prices', ARRAY['Financial', 'Market'], ARRAY['market', 'volatility', 'interest rate', 'FX', 'currency'], ARRAY['financial_services', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-FN-004', 'Excessive leverage', 'High debt levels creating financial stress', ARRAY['Financial', 'Leverage'], ARRAY['leverage', 'debt', 'borrowing', 'covenant'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-FN-005', 'Budgetary pressures', 'Cost overruns or revenue shortfalls', ARRAY['Financial', 'Budget'], ARRAY['budget', 'cost', 'revenue', 'variance'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-FN-006', 'Inadequate financial controls', 'Weak financial reporting or internal audit', ARRAY['Financial', 'Controls', 'Governance'], ARRAY['financial controls', 'reporting', 'audit', 'accounting'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-FN-007', 'Foreign exchange exposure', 'Unhedged currency risk from international operations', ARRAY['Financial', 'FX', 'Market'], ARRAY['FX', 'currency', 'foreign exchange', 'hedging'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-FN-008', 'Fraud or embezzlement', 'Internal or external financial fraud', ARRAY['Financial', 'Fraud', 'Governance'], ARRAY['fraud', 'embezzlement', 'theft', 'misappropriation'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-FN-009', 'Investment underperformance', 'Poor returns on strategic investments', ARRAY['Financial', 'Investment'], ARRAY['investment', 'returns', 'portfolio', 'capital'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-FN-010', 'Revenue concentration', 'Over-dependence on single revenue stream', ARRAY['Financial', 'Concentration'], ARRAY['revenue', 'concentration', 'product', 'dependency'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-FN-011', 'Tax compliance issues', 'Errors or disputes in tax matters', ARRAY['Financial', 'Tax', 'Compliance'], ARRAY['tax', 'compliance', 'filing', 'audit'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-FN-012', 'Interest rate risk', 'Exposure to interest rate fluctuations', ARRAY['Financial', 'Interest Rate'], ARRAY['interest rate', 'rate risk', 'yield', 'duration'], ARRAY['financial_services', 'banking', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-FN-013', 'Capital adequacy issues', 'Insufficient capital buffers', ARRAY['Financial', 'Capital'], ARRAY['capital', 'adequacy', 'buffer', 'regulatory capital'], ARRAY['financial_services', 'banking', 'insurance', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-FN-014', 'Pension liability risks', 'Unfunded pension obligations', ARRAY['Financial', 'Pension'], ARRAY['pension', 'liability', 'retirement', 'benefits'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-FN-015', 'Asset valuation errors', 'Incorrect valuation of assets', ARRAY['Financial', 'Valuation'], ARRAY['valuation', 'asset', 'impairment', 'fair value'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),

-- COMPLIANCE & LEGAL RISK (15)
('root_cause', 'RC-CL-001', 'Regulatory changes', 'New or changing laws requiring compliance', ARRAY['Compliance', 'Legal', 'Regulatory'], ARRAY['regulatory', 'regulation', 'law', 'compliance'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CL-002', 'Non-compliance with regulations', 'Failure to adhere to applicable laws or standards', ARRAY['Compliance', 'Legal', 'Regulatory'], ARRAY['non-compliance', 'violation', 'breach', 'regulatory'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CL-003', 'Legal disputes or litigation', 'Lawsuits or disputes with stakeholders', ARRAY['Compliance', 'Legal'], ARRAY['litigation', 'lawsuit', 'dispute', 'legal'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CL-004', 'Contractual failures', 'Breach of contract terms or disputes', ARRAY['Compliance', 'Legal', 'Contract'], ARRAY['contract', 'breach', 'obligation', 'agreement'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CL-005', 'Sanctions or trade restrictions', 'International sanctions or export controls', ARRAY['Compliance', 'Legal', 'Geopolitical'], ARRAY['sanctions', 'export', 'trade', 'restrictions'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CL-006', 'Anti-bribery and corruption violations', 'Violations of FCPA, UK Bribery Act, or local laws', ARRAY['Compliance', 'Legal', 'Governance'], ARRAY['bribery', 'corruption', 'FCPA', 'ethics'], ARRAY['universal'], '{"severity_indicator": "Critical"}'::jsonb),
('root_cause', 'RC-CL-007', 'Data privacy violations', 'Non-compliance with GDPR, CCPA, or data protection', ARRAY['Compliance', 'Privacy', 'Data'], ARRAY['privacy', 'GDPR', 'data protection', 'PII'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CL-008', 'Intellectual property disputes', 'Patent, trademark, or copyright issues', ARRAY['Compliance', 'Legal', 'IP'], ARRAY['IP', 'patent', 'trademark', 'copyright'], ARRAY['technology', 'pharmaceuticals', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CL-009', 'Employment law violations', 'Issues with labor laws or workplace regulations', ARRAY['Compliance', 'Legal', 'HR'], ARRAY['employment', 'labor', 'workplace', 'discrimination'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CL-010', 'Environmental regulation violations', 'Non-compliance with environmental laws', ARRAY['Compliance', 'Environmental', 'ESG'], ARRAY['environmental', 'emissions', 'pollution', 'EPA'], ARRAY['manufacturing', 'energy_utilities', 'mining', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CL-011', 'Health and safety violations', 'Non-compliance with workplace safety regulations', ARRAY['Compliance', 'Health', 'Safety'], ARRAY['health', 'safety', 'OSHA', 'workplace'], ARRAY['manufacturing', 'construction', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CL-012', 'Product liability issues', 'Defective products causing harm or recalls', ARRAY['Compliance', 'Legal', 'Product'], ARRAY['product liability', 'recall', 'defect', 'safety'], ARRAY['manufacturing', 'consumer_goods', 'pharmaceuticals', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-CL-013', 'Licensing non-compliance', 'Operating without proper licenses or permits', ARRAY['Compliance', 'Legal'], ARRAY['license', 'permit', 'authorization', 'registration'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CL-014', 'Conflicts of interest', 'Undisclosed or unmanaged conflicts of interest', ARRAY['Compliance', 'Governance', 'Ethics'], ARRAY['conflict of interest', 'disclosure', 'ethics', 'governance'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-CL-015', 'Whistleblower complaints', 'Allegations of misconduct from whistleblowers', ARRAY['Compliance', 'Governance', 'Ethics'], ARRAY['whistleblower', 'complaint', 'allegation', 'investigation'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),

-- PEOPLE & HR RISK (12)
('root_cause', 'RC-PE-001', 'Leadership failures', 'Ineffective executive leadership or misconduct', ARRAY['People', 'Human Capital', 'Leadership', 'Governance'], ARRAY['leadership', 'executive', 'management', 'governance'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-PE-002', 'Talent shortage or turnover', 'Inability to attract or retain skilled employees', ARRAY['People', 'Human Capital', 'HR'], ARRAY['talent', 'turnover', 'retention', 'recruitment'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-003', 'Inadequate training', 'Insufficient employee development programs', ARRAY['People', 'Human Capital', 'Training'], ARRAY['training', 'development', 'skills', 'competency'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-004', 'Poor organizational culture', 'Toxic work environment or values misalignment', ARRAY['People', 'Human Capital', 'Culture'], ARRAY['culture', 'morale', 'values', 'workplace'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-005', 'Succession planning gaps', 'Lack of pipeline for leadership roles', ARRAY['People', 'Human Capital', 'Succession'], ARRAY['succession', 'pipeline', 'leadership', 'continuity'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-006', 'Employee misconduct', 'Unethical behavior or policy violations', ARRAY['People', 'Human Capital', 'Ethics'], ARRAY['misconduct', 'ethics', 'policy violation', 'discipline'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-007', 'Health and safety failures', 'Inadequate workplace safety programs', ARRAY['People', 'Human Capital', 'Safety'], ARRAY['health', 'safety', 'injury', 'workplace'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-PE-008', 'Key person dependency', 'Critical reliance on specific individuals', ARRAY['People', 'Human Capital', 'Concentration'], ARRAY['key person', 'dependency', 'critical', 'single point'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-009', 'Burnout and fatigue', 'Employee exhaustion impacting performance', ARRAY['People', 'Human Capital', 'Wellbeing'], ARRAY['burnout', 'fatigue', 'stress', 'wellbeing'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-010', 'Diversity and inclusion issues', 'Lack of diverse workforce or inclusive culture', ARRAY['People', 'Human Capital', 'D&I'], ARRAY['diversity', 'inclusion', 'DEI', 'bias'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-011', 'Labor relations issues', 'Union disputes or industrial actions', ARRAY['People', 'Human Capital', 'Labor'], ARRAY['union', 'labor', 'strike', 'industrial action'], ARRAY['manufacturing', 'transportation_logistics', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-PE-012', 'Remote work challenges', 'Issues from distributed or hybrid workforce', ARRAY['People', 'Human Capital', 'Remote'], ARRAY['remote', 'hybrid', 'work from home', 'distributed'], ARRAY['universal'], '{"severity_indicator": "Low"}'::jsonb),

-- GOVERNANCE RISK (10)
('root_cause', 'RC-GV-001', 'Poor board oversight', 'Inadequate governance by board of directors', ARRAY['Governance', 'Board', 'Corporate Governance'], ARRAY['board', 'oversight', 'governance', 'directors'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-GV-002', 'Weak internal audit function', 'Ineffective internal audit processes', ARRAY['Governance', 'Audit', 'Controls'], ARRAY['internal audit', 'assurance', 'controls', 'testing'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GV-003', 'Inadequate risk management framework', 'Poor enterprise risk management practices', ARRAY['Governance', 'Risk Management'], ARRAY['risk management', 'ERM', 'framework', 'methodology'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GV-004', 'Policy compliance failures', 'Non-adherence to internal policies', ARRAY['Governance', 'Policy', 'Compliance'], ARRAY['policy', 'compliance', 'internal', 'adherence'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GV-005', 'Inadequate disclosure and transparency', 'Insufficient reporting to stakeholders', ARRAY['Governance', 'Disclosure', 'Transparency'], ARRAY['disclosure', 'transparency', 'reporting', 'stakeholder'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GV-006', 'Ethical breaches', 'Violations of ethical standards', ARRAY['Governance', 'Ethics'], ARRAY['ethics', 'integrity', 'values', 'conduct'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-GV-007', 'Stakeholder management failures', 'Poor engagement with key stakeholders', ARRAY['Governance', 'Stakeholder'], ARRAY['stakeholder', 'engagement', 'communication', 'relationship'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GV-008', 'Unclear accountability', 'Ambiguous roles and responsibilities', ARRAY['Governance', 'Accountability'], ARRAY['accountability', 'responsibility', 'roles', 'RACI'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GV-009', 'Decision-making failures', 'Poor governance over key decisions', ARRAY['Governance', 'Decision Making'], ARRAY['decision', 'governance', 'approval', 'authority'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GV-010', 'Communications breakdown', 'Inadequate internal or external communications', ARRAY['Governance', 'Communication'], ARRAY['communication', 'information', 'messaging', 'channels'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),

-- THIRD-PARTY / VENDOR RISK (8)
('root_cause', 'RC-TP-001', 'Vendor failure or default', 'Critical vendor unable to deliver services', ARRAY['Third Party', 'Vendor', 'Supply Chain'], ARRAY['vendor', 'supplier', 'default', 'failure'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-TP-002', 'Inadequate vendor due diligence', 'Insufficient vetting of vendors', ARRAY['Third Party', 'Vendor', 'Due Diligence'], ARRAY['due diligence', 'vetting', 'assessment', 'vendor'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-TP-003', 'Vendor concentration', 'Over-reliance on single or few vendors', ARRAY['Third Party', 'Vendor', 'Concentration'], ARRAY['concentration', 'dependency', 'single vendor', 'reliance'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-TP-004', 'Vendor compliance issues', 'Third parties not meeting regulatory standards', ARRAY['Third Party', 'Vendor', 'Compliance'], ARRAY['compliance', 'regulation', 'standard', 'vendor'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-TP-005', 'Subcontractor risks', 'Risks from vendors subcontracting work', ARRAY['Third Party', 'Vendor', 'Subcontractor'], ARRAY['subcontractor', 'fourth party', 'outsourcing', 'delegation'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-TP-006', 'Vendor SLA breaches', 'Third parties not meeting service levels', ARRAY['Third Party', 'Vendor', 'SLA'], ARRAY['SLA', 'service level', 'performance', 'contract'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-TP-007', 'Outsourcing failures', 'Problems with outsourced business functions', ARRAY['Third Party', 'Outsourcing'], ARRAY['outsourcing', 'BPO', 'offshoring', 'managed services'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-TP-008', 'Vendor financial instability', 'Vendors facing financial distress', ARRAY['Third Party', 'Vendor', 'Financial'], ARRAY['financial', 'bankruptcy', 'insolvency', 'viability'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),

-- ENVIRONMENTAL & ESG RISK (10)
('root_cause', 'RC-EN-001', 'Climate change impacts', 'Physical risks from extreme weather or climate changes', ARRAY['Environmental', 'ESG', 'Climate'], ARRAY['climate', 'weather', 'physical risk', 'natural disaster'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-EN-002', 'Carbon transition risk', 'Business model disruption from low-carbon transition', ARRAY['Environmental', 'ESG', 'Climate'], ARRAY['carbon', 'transition', 'net zero', 'emissions'], ARRAY['energy_utilities', 'oil_gas', 'manufacturing', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-EN-003', 'Environmental violations', 'Non-compliance with environmental regulations', ARRAY['Environmental', 'ESG', 'Compliance'], ARRAY['environmental', 'compliance', 'pollution', 'emissions'], ARRAY['manufacturing', 'mining', 'energy_utilities', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-EN-004', 'ESG performance gaps', 'Poor environmental or social performance', ARRAY['Environmental', 'ESG'], ARRAY['ESG', 'sustainability', 'rating', 'performance'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-EN-005', 'Resource scarcity', 'Limited availability of natural resources', ARRAY['Environmental', 'ESG', 'Supply Chain'], ARRAY['resource', 'scarcity', 'water', 'materials'], ARRAY['manufacturing', 'agriculture', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-EN-006', 'Waste management issues', 'Problems with waste disposal or recycling', ARRAY['Environmental', 'ESG'], ARRAY['waste', 'disposal', 'recycling', 'hazardous'], ARRAY['manufacturing', 'healthcare', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-EN-007', 'Social responsibility failures', 'Human rights or community issues', ARRAY['Environmental', 'ESG', 'Social'], ARRAY['social', 'human rights', 'community', 'responsibility'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-EN-008', 'Biodiversity loss', 'Impacts on ecosystems and species', ARRAY['Environmental', 'ESG'], ARRAY['biodiversity', 'ecosystem', 'species', 'habitat'], ARRAY['agriculture', 'mining', 'energy_utilities', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-EN-009', 'Water management issues', 'Water usage, quality, or scarcity problems', ARRAY['Environmental', 'ESG'], ARRAY['water', 'usage', 'scarcity', 'quality'], ARRAY['manufacturing', 'agriculture', 'mining', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-EN-010', 'Sustainable supply chain failures', 'Unsustainable practices in supply chain', ARRAY['Environmental', 'ESG', 'Supply Chain'], ARRAY['sustainable', 'supply chain', 'sourcing', 'ethical'], ARRAY['retail', 'consumer_goods', 'manufacturing', 'universal'], '{"severity_indicator": "Medium"}'::jsonb),

-- GEOPOLITICAL & EXTERNAL RISK (10)
('root_cause', 'RC-GE-001', 'Political instability', 'Political unrest or regime changes in operating regions', ARRAY['Geopolitical', 'External', 'Political'], ARRAY['political', 'instability', 'regime', 'government'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-GE-002', 'Trade wars or tariffs', 'International trade conflicts affecting commerce', ARRAY['Geopolitical', 'External', 'Trade'], ARRAY['trade', 'tariff', 'protectionism', 'trade war'], ARRAY['manufacturing', 'retail', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-GE-003', 'Geopolitical conflicts', 'Wars or armed conflicts disrupting operations', ARRAY['Geopolitical', 'External', 'Conflict'], ARRAY['war', 'conflict', 'geopolitical', 'military'], ARRAY['universal'], '{"severity_indicator": "Critical"}'::jsonb),
('root_cause', 'RC-GE-004', 'Pandemic or public health crisis', 'Disease outbreaks disrupting business', ARRAY['Geopolitical', 'External', 'Health'], ARRAY['pandemic', 'health crisis', 'disease', 'outbreak'], ARRAY['universal'], '{"severity_indicator": "Critical"}'::jsonb),
('root_cause', 'RC-GE-005', 'Terrorism or civil unrest', 'Security threats from terrorism or protests', ARRAY['Geopolitical', 'External', 'Security'], ARRAY['terrorism', 'civil unrest', 'protest', 'security'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-GE-006', 'Currency devaluation', 'Significant currency depreciation in key markets', ARRAY['Geopolitical', 'External', 'Financial'], ARRAY['currency', 'devaluation', 'depreciation', 'exchange rate'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GE-007', 'Expropriation or nationalization', 'Government seizure of assets', ARRAY['Geopolitical', 'External', 'Political'], ARRAY['expropriation', 'nationalization', 'seizure', 'government'], ARRAY['energy_utilities', 'mining', 'oil_gas', 'universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-GE-008', 'Natural disasters', 'Earthquakes, floods, hurricanes, or other disasters', ARRAY['Geopolitical', 'External', 'Natural'], ARRAY['natural disaster', 'earthquake', 'flood', 'hurricane'], ARRAY['universal'], '{"severity_indicator": "High"}'::jsonb),
('root_cause', 'RC-GE-009', 'Infrastructure disruption', 'Failure of public infrastructure (power, communications)', ARRAY['Geopolitical', 'External', 'Infrastructure'], ARRAY['infrastructure', 'power', 'utilities', 'communications'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb),
('root_cause', 'RC-GE-010', 'Social or demographic shifts', 'Major changes in population or society', ARRAY['Geopolitical', 'External', 'Social'], ARRAY['demographic', 'population', 'social', 'migration'], ARRAY['universal'], '{"severity_indicator": "Medium"}'::jsonb)

ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category_hints = EXCLUDED.category_hints,
  keyword_hints = EXCLUDED.keyword_hints,
  industry_tags = EXCLUDED.industry_tags,
  metadata = EXCLUDED.metadata,
  updated_at = NOW();

-- Verification
DO $$
DECLARE v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM seed_master_library WHERE library_type = 'root_cause';
  RAISE NOTICE '✓ Root causes seeded: % records', v_count;
END $$;
