-- Migration: Add Industry Type to Organizations
-- Description: Add industry_type column for taxonomy-aware library seeding
-- Feature Branch: feature/comprehensive-global-libraries
-- Date: 2026-01-08

-- ============================================================================
-- PART 1: ADD INDUSTRY TYPE COLUMN
-- ============================================================================

ALTER TABLE organizations 
  ADD COLUMN IF NOT EXISTS industry_type VARCHAR(50)
  CHECK (industry_type IN (
    'financial_services',
    'banking',
    'insurance',
    'asset_management',
    'healthcare',
    'pharmaceuticals',
    'manufacturing',
    'technology',
    'telecommunications',
    'energy_utilities',
    'oil_gas',
    'mining',
    'retail',
    'consumer_goods',
    'transportation_logistics',
    'real_estate',
    'construction',
    'agriculture',
    'hospitality_tourism',
    'media_entertainment',
    'education',
    'professional_services',
    'government_public_sector',
    'non_profit',
    'defense_aerospace',
    'other'
  ));

-- Default comment
COMMENT ON COLUMN organizations.industry_type IS 
  'Industry sector for the organization. Used for taxonomy-aware library seeding and industry-specific risk data.';

-- ============================================================================
-- PART 2: CREATE MASTER SEED LIBRARY TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS seed_master_library (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Type: root_cause, impact, control, kri, kci
  library_type VARCHAR(20) NOT NULL CHECK (library_type IN ('root_cause', 'impact', 'control', 'kri', 'kci')),
  
  -- Identifiers
  code VARCHAR(30) UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  
  -- Matching hints (for dynamic taxonomy matching)
  category_hints TEXT[] DEFAULT ARRAY[]::TEXT[],       -- Standard categories this might match
  subcategory_hints TEXT[] DEFAULT ARRAY[]::TEXT[],    -- Subcategories this might match
  keyword_hints TEXT[] DEFAULT ARRAY[]::TEXT[],        -- Keywords for AI matching
  
  -- Industry applicability
  industry_tags TEXT[] DEFAULT ARRAY['universal']::TEXT[],  -- Which industries this applies to
  is_universal BOOLEAN DEFAULT true,                         -- Applies to all industries?
  
  -- Type-specific metadata (stored as JSONB for flexibility)
  metadata JSONB DEFAULT '{}'::JSONB,
  -- For root_cause: { severity_indicator, parent_code }
  -- For impact: { severity_level, impact_type, financial_range_min, financial_range_max }
  -- For control: { control_type, dime_scores, automation_level }
  -- For kri/kci: { measurement_unit, frequency, warning_threshold, critical_threshold }
  
  -- Relationships (for mappings)
  related_codes TEXT[] DEFAULT ARRAY[]::TEXT[],  -- Related cause/KRI/KCI codes
  
  -- Source and versioning
  source VARCHAR(100),  -- COSO, ISO 31000, Basel, custom, etc.
  version INTEGER DEFAULT 1,
  is_active BOOLEAN DEFAULT true,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_seed_master_library_type ON seed_master_library(library_type);
CREATE INDEX IF NOT EXISTS idx_seed_master_industry ON seed_master_library USING GIN(industry_tags);
CREATE INDEX IF NOT EXISTS idx_seed_master_categories ON seed_master_library USING GIN(category_hints);
CREATE INDEX IF NOT EXISTS idx_seed_master_keywords ON seed_master_library USING GIN(keyword_hints);
CREATE INDEX IF NOT EXISTS idx_seed_master_code ON seed_master_library(code);

-- Comments
COMMENT ON TABLE seed_master_library IS 
  'Master reference library containing all possible root causes, impacts, controls, and KRIs/KCIs. Used by Library Generator to seed org-specific global libraries based on taxonomy and industry.';

-- ============================================================================
-- PART 3: CREATE LIBRARY GENERATION TRACKING TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS library_generation_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  
  -- Generation details
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  generated_by UUID REFERENCES user_profiles(id),
  
  -- What was generated
  industry_type VARCHAR(50),
  categories_used TEXT[],
  
  -- Results
  root_causes_generated INTEGER DEFAULT 0,
  impacts_generated INTEGER DEFAULT 0,
  controls_generated INTEGER DEFAULT 0,
  kris_generated INTEGER DEFAULT 0,
  kcis_generated INTEGER DEFAULT 0,
  ai_generated_count INTEGER DEFAULT 0,  -- Items generated by AI (not in master)
  
  -- Metadata
  generation_mode VARCHAR(20) CHECK (generation_mode IN ('initial', 'refresh', 'ai_suggestion')),
  status VARCHAR(20) CHECK (status IN ('completed', 'partial', 'failed')),
  error_message TEXT
);

-- Index for tracking
CREATE INDEX IF NOT EXISTS idx_library_gen_org ON library_generation_log(organization_id);
CREATE INDEX IF NOT EXISTS idx_library_gen_date ON library_generation_log(generated_at DESC);

-- Enable RLS
ALTER TABLE library_generation_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their org's generation log"
  ON library_generation_log FOR SELECT
  USING (organization_id IN (
    SELECT organization_id FROM user_profiles WHERE id = auth.uid()
  ));

CREATE POLICY "Admins can insert generation log"
  ON library_generation_log FOR INSERT
  WITH CHECK (organization_id IN (
    SELECT organization_id FROM user_profiles 
    WHERE id = auth.uid() AND role IN ('primary_admin', 'secondary_admin')
  ));

COMMENT ON TABLE library_generation_log IS 
  'Tracks library generation events for auditing and refresh management.';

-- ============================================================================
-- VERIFICATION
-- ============================================================================

DO $$
BEGIN
  -- Check industry_type column exists
  IF EXISTS (
    SELECT FROM information_schema.columns 
    WHERE table_name = 'organizations' AND column_name = 'industry_type'
  ) THEN
    RAISE NOTICE '✓ industry_type column added to organizations';
  ELSE
    RAISE WARNING '✗ industry_type column NOT added';
  END IF;
  
  -- Check seed_master_library exists
  IF EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_name = 'seed_master_library'
  ) THEN
    RAISE NOTICE '✓ seed_master_library table created';
  ELSE
    RAISE WARNING '✗ seed_master_library table NOT created';
  END IF;
  
  -- Check library_generation_log exists
  IF EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_name = 'library_generation_log'
  ) THEN
    RAISE NOTICE '✓ library_generation_log table created';
  ELSE
    RAISE WARNING '✗ library_generation_log table NOT created';
  END IF;
END $$;
